version: "3.8"
services:
  shinyapps:
    build: .

    ports:
      - "3838:3838" # host:container
    container_name: shinyapps
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodba
  mongodba:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongodba
    volumes:
      #- ./data/db:/data/db:ro
     # - ./TrialCurate/data/trials:/data/trials
     # - ./TrialCurate/mongo/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh:ro
       - ./data/trials:/data/trials
       - ./mongo/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh:ro




